# Base: PostgreSQL oficial (tem pg_dump)
FROM postgres:latest

# Instalar dependências mínimas + AWS CLI
USER root
RUN apt-get update && \
    apt-get install -y python3 python3-pip curl unzip apt-utils ca-certificates && \
    pip3 install --no-cache-dir awscli --break-system-packages && \
    rm -rf /var/lib/apt/lists/*

# Volumes para armazenar backups
VOLUME ["/backups"]

# Mantém o container rodando com cron configurado via docker-compose
ENTRYPOINT ["/bin/sh", "-c"]
