@HostAddress = http://localhost:5037
@BearerToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjExIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwianRpIjoiYWMwMGE2ZjktZWM3Zi00MTFhLTk5MDYtMDI2ZjE2ZTdlYmY5IiwiZXhwIjoxNzQ1NTkyMDUwLCJpc3MiOiJmaW5hbnRlY2guY29tLmJyIiwiYXVkIjoiaHR0cDovL2ZpbmFudGVjaC5jb20uYnIifQ.A_gIWPGoA7cb4h0Kr5Qd-IYHTb3xmqpKsMYkF3LgZNM

###

//
// USERCONTROLLER
//
POST {{HostAddress}}/api/User/CreateUser
Content-Type: application/json

{
  "Name": "Usuário teste",
  "Email": "test@test.com",
  "Password": "test123"
}
###


//
// USERCONTROLLER
//

POST {{HostAddress}}/api/Auth/Authenticate
Content-Type: application/json

{
  "Email": "test@test.com",
  "Password": "test123"
}
###


//
// USERCONTROLLER
//

POST {{HostAddress}}/api/Account/CreateAccount
Content-Type: application/json
Authorization: {{BearerToken}}

{
  "Balance": 1000,
  "Bank": "NunBank",
  "Description": "Conta teste",
  "AccountType": 1,
  "Color": "#AA2F1A"
}
###

GET {{HostAddress}}/api/Account
Content-Type: application/json
Authorization: {{BearerToken}}
###

PATCH {{HostAddress}}/api/Account/UpdateAccount
Content-Type: application/json
Authorization: {{BearerToken}}

{
  "Id": 4,
  "Bank": "Nubank",
  "Description": "Conta teste: corrigida",
  "AccountType": 2,
  "Color": "#AA2F1A"
}
###

//
//  TRANSACTIONCONTROLLER
//
  

POST {{HostAddress}}/api/Transaction/CreateExpense
Content-Type: application/json
Authorization: {{BearerToken}}

{
  "Amount": 100,
  "ExpenseType": 0,
  "PurchaseDate": "2024-04-26T13:16:07.448Z",
  "Destination": "Livraria Santana",
  "Description": "Harry Potter Coleção",
  "JustForRecord": false,
  "AccountId": 4,
  "CategoryId": 0
}
###

DELETE {{HostAddress}}/api/Transaction/DeleteExpense/4
Content-Type: application/json
Authorization: {{BearerToken}}
###

PATCH {{HostAddress}}/api/Transaction/UpdateExpense
Content-Type: application/json
Authorization: {{BearerToken}}

{
  "Id": 5,
  "PurchaseDate": "2024-04-22T13:16:07.448Z",
  "Destination": "Livraria Saraiva",
  "Description": "Harry Potter Coleção de Livros"
}
###


// INCOME

POST {{HostAddress}}/api/Transaction/CreateIncome
Content-Type: application/json
Authorization: {{BearerToken}}

{
  "Amount": 100,
  "ExpenseType": 0,
  "PurchaseDate": "2024-04-26T13:16:07.448Z",
  "Origin": "Imperio soft LTDA",
  "Description": "Salário mensal",
  "JustForRecord": false,
  "AccountId": 4,
  "CategoryId": 0
}
###

DELETE {{HostAddress}}/api/Transaction/DeleteIncome/1
Content-Type: application/json
Authorization: {{BearerToken}}
###

PATCH {{HostAddress}}/api/Transaction/UpdateIncome
Content-Type: application/json
Authorization: {{BearerToken}}

{
  "Id": 1,
  "PurchaseDate": "2024-04-22T13:16:07.448Z",
  "Origin": "Imperios soft LTDA",
  "Description": "Salário do mês"
}
###

// TRANSFENCES
POST {{HostAddress}}/api/Transaction/CreateTransference
Content-Type: application/json
Authorization: {{BearerToken}}

{
  "Description": "transferencia teste",
  "Amount": 200,
  "PurchaseDate": "2024-05-02T13:16:07.448Z",
  "AccountDestinyId": 3,
  "AccountOriginId": 4
}
###
// TRANSACTIONS: pageNumber,startDate, endDate, accountId

GET {{HostAddress}}/api/Transaction/GetTransactionsWithPagination?pageNumber=1
Authorization: {{BearerToken}}
###

//
//   CATEGORYCONTROLLER
//

POST {{HostAddress}}/api/Category/CreateCategory
Content-Type: application/json
Authorization: {{BearerToken}}

{
  "Name": "Compas",
  "Icon": "icon",
  "Color": "#E30A31",
  "BillType": 0
}
###

GET {{HostAddress}}/api/Category/GetAllCategories
Authorization: {{BearerToken}}
###

PATCH {{HostAddress}}/api/Category/UpdateCategory
Content-Type: application/json
Authorization: {{BearerToken}}

{
  "Id": 0,
  "Name": "Compras",
  "color": "#AD451D"
}
###

DELETE {{HostAddress}}/api/Category/DeleteCategory/2
Authorization: {{BearerToken}}
###


//
// CREDITCARDCONTROLLER
//

POST {{HostAddress}}/api/CreditCard/CreateCreditCard
Content-Type: application/json
Authorization: {{BearerToken}}

{
  "totalLimit": 1000,
  "usedLimit": 0,
  "description": "Cartão do Nubank",
  "cardBrand": "MasterCard",
  "accountId": 4,
  "closeDay": 3,
  "dueDay": 10
}
###

PATCH {{HostAddress}}/api/CreditCard/UpdateCreditCard
Content-Type: application/json
Authorization: {{BearerToken}}

{
  "id": 1,
  "description": "Cartão atualizado",
  "cardBrand": "master card"
}
###

POST {{HostAddress}}/api/CreditCard/CreateCreditPurchase
Content-Type: application/json
Authorization: {{BearerToken}}

{
  "totalAmount": 100,
  "totalInstallment": 1,
  "installmentsPaid": 0,
  "purchaseDate": "2024-04-30T01:48:44.848Z",
  "destination": "bom lar",
  "description": "compras de casa",
  "creditCardId": 1,
  "categoryId": 0
}
###

GET {{HostAddress}}/api/CreditCard/GetInvoicesWithPagination
Authorization: {{BearerToken}}
###

POST {{HostAddress}}/api/CreditCard/PayInvoice
Content-Type: application/json
Authorization: {{BearerToken}}

{
  "amountPaid": 50,
  "description": "pagamento de 50 da fatura",
  "paymentDate": "2024-04-20T20:05:09.367Z",
  "invoiceId": 508,
  "accountPaidId": 4
}
###

DELETE {{HostAddress}}/api/CreditCard/DeleteCreditPurchase/8
Authorization: {{BearerToken}}
###